server:
  port: 8080

spring:
  application:
    name: transaction-service
  data:
    mongodb:
      database: mt
      uri: mongodb://mongodbuser:123123@localhost:27017/?authSource=admin&readPreference=primary&appname=MongoDB%20Compass&directConnection=true&ssl=false
  cloud:
    stream:
      function:
        routing:
          enabled: true
        definition: functionRouter
      kafka:
        default:
          consumer:
            startOffset: latest
            resetOffsets: true
        binder:
          brokers: localhost:9092
          autoCreateTopics: false
      bindings:
        functionRouter-in-0:
          destination: mt.events.pub
          group: mt-${spring.application.name}
        money-transfer-events-out:
          destination: mt.events.pub


service:
  client:
    account:
      url: localhost:8090/api/v1/account
    reservation:
      url: localhost:8090/api/v1/reservation
  eventBindings:
    TransactionSent: transactionSentListener
    TransactionSucceed: transactionSucceedListener
    TransactionRejected: transactionRejectListener
    TransactionError: transactionErrorListener
